# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from binance_market_data.gateway.v1 import gateway_messages_pb2 as binance__market__data_dot_gateway_dot_v1_dot_gateway__messages__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in binance_market_data/gateway/v1/gateway_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BinanceMarketDataGatewayServiceStub:
    """BinanceMarketDataGatewayService provides streaming market data subscriptions.

    V1 RPCs:
    - SubscribeEvents: contiguous real-time event stream (DepthUpdate, AggTrade, BookTicker)
    - SubscribeOrderBook: order book snapshot + diff stream
    - SubscribeMarketState: latest market state stream
    - GetGatewayStatus: one-shot operational status query

    V1 does NOT include: trading, account, strategy, client-streaming,
    bidirectional streaming, historical replay, or recorder RPCs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeEvents = channel.unary_stream(
                '/binance_market_data.gateway.v1.BinanceMarketDataGatewayService/SubscribeEvents',
                request_serializer=binance__market__data_dot_gateway_dot_v1_dot_gateway__messages__pb2.EventSubscriptionRequest.SerializeToString,
                response_deserializer=binance__market__data_dot_gateway_dot_v1_dot_gateway__messages__pb2.GatewayEventEnvelope.FromString,
                _registered_method=True)
        self.SubscribeOrderBook = channel.unary_stream(
                '/binance_market_data.gateway.v1.BinanceMarketDataGatewayService/SubscribeOrderBook',
                request_serializer=binance__market__data_dot_gateway_dot_v1_dot_gateway__messages__pb2.OrderBookSubscriptionRequest.SerializeToString,
                response_deserializer=binance__market__data_dot_gateway_dot_v1_dot_gateway__messages__pb2.OrderBookStreamItem.FromString,
                _registered_method=True)
        self.SubscribeMarketState = channel.unary_stream(
                '/binance_market_data.gateway.v1.BinanceMarketDataGatewayService/SubscribeMarketState',
                request_serializer=binance__market__data_dot_gateway_dot_v1_dot_gateway__messages__pb2.MarketStateSubscriptionRequest.SerializeToString,
                response_deserializer=binance__market__data_dot_gateway_dot_v1_dot_gateway__messages__pb2.MarketStateStreamItem.FromString,
                _registered_method=True)
        self.GetGatewayStatus = channel.unary_unary(
                '/binance_market_data.gateway.v1.BinanceMarketDataGatewayService/GetGatewayStatus',
                request_serializer=binance__market__data_dot_gateway_dot_v1_dot_gateway__messages__pb2.GatewayStatusRequest.SerializeToString,
                response_deserializer=binance__market__data_dot_gateway_dot_v1_dot_gateway__messages__pb2.GatewayStatusSnapshot.FromString,
                _registered_method=True)


class BinanceMarketDataGatewayServiceServicer:
    """BinanceMarketDataGatewayService provides streaming market data subscriptions.

    V1 RPCs:
    - SubscribeEvents: contiguous real-time event stream (DepthUpdate, AggTrade, BookTicker)
    - SubscribeOrderBook: order book snapshot + diff stream
    - SubscribeMarketState: latest market state stream
    - GetGatewayStatus: one-shot operational status query

    V1 does NOT include: trading, account, strategy, client-streaming,
    bidirectional streaming, historical replay, or recorder RPCs.
    """

    def SubscribeEvents(self, request, context):
        """Subscribe to a contiguous event stream.
        Delivery mode: CONTIGUOUS_EVENTS. No silent message dropping.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeOrderBook(self, request, context):
        """Subscribe to an order book snapshot + diff stream.
        Initial snapshot is required before live depth updates begin.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeMarketState(self, request, context):
        """Subscribe to latest market state updates.
        Delivery mode: LATEST_STATE. Intermediate states may be overwritten.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGatewayStatus(self, request, context):
        """Get a one-shot snapshot of Gateway operational status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BinanceMarketDataGatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=binance__market__data_dot_gateway_dot_v1_dot_gateway__messages__pb2.EventSubscriptionRequest.FromString,
                    response_serializer=binance__market__data_dot_gateway_dot_v1_dot_gateway__messages__pb2.GatewayEventEnvelope.SerializeToString,
            ),
            'SubscribeOrderBook': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeOrderBook,
                    request_deserializer=binance__market__data_dot_gateway_dot_v1_dot_gateway__messages__pb2.OrderBookSubscriptionRequest.FromString,
                    response_serializer=binance__market__data_dot_gateway_dot_v1_dot_gateway__messages__pb2.OrderBookStreamItem.SerializeToString,
            ),
            'SubscribeMarketState': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeMarketState,
                    request_deserializer=binance__market__data_dot_gateway_dot_v1_dot_gateway__messages__pb2.MarketStateSubscriptionRequest.FromString,
                    response_serializer=binance__market__data_dot_gateway_dot_v1_dot_gateway__messages__pb2.MarketStateStreamItem.SerializeToString,
            ),
            'GetGatewayStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGatewayStatus,
                    request_deserializer=binance__market__data_dot_gateway_dot_v1_dot_gateway__messages__pb2.GatewayStatusRequest.FromString,
                    response_serializer=binance__market__data_dot_gateway_dot_v1_dot_gateway__messages__pb2.GatewayStatusSnapshot.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'binance_market_data.gateway.v1.BinanceMarketDataGatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('binance_market_data.gateway.v1.BinanceMarketDataGatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BinanceMarketDataGatewayService:
    """BinanceMarketDataGatewayService provides streaming market data subscriptions.

    V1 RPCs:
    - SubscribeEvents: contiguous real-time event stream (DepthUpdate, AggTrade, BookTicker)
    - SubscribeOrderBook: order book snapshot + diff stream
    - SubscribeMarketState: latest market state stream
    - GetGatewayStatus: one-shot operational status query

    V1 does NOT include: trading, account, strategy, client-streaming,
    bidirectional streaming, historical replay, or recorder RPCs.
    """

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/binance_market_data.gateway.v1.BinanceMarketDataGatewayService/SubscribeEvents',
            binance__market__data_dot_gateway_dot_v1_dot_gateway__messages__pb2.EventSubscriptionRequest.SerializeToString,
            binance__market__data_dot_gateway_dot_v1_dot_gateway__messages__pb2.GatewayEventEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeOrderBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/binance_market_data.gateway.v1.BinanceMarketDataGatewayService/SubscribeOrderBook',
            binance__market__data_dot_gateway_dot_v1_dot_gateway__messages__pb2.OrderBookSubscriptionRequest.SerializeToString,
            binance__market__data_dot_gateway_dot_v1_dot_gateway__messages__pb2.OrderBookStreamItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeMarketState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/binance_market_data.gateway.v1.BinanceMarketDataGatewayService/SubscribeMarketState',
            binance__market__data_dot_gateway_dot_v1_dot_gateway__messages__pb2.MarketStateSubscriptionRequest.SerializeToString,
            binance__market__data_dot_gateway_dot_v1_dot_gateway__messages__pb2.MarketStateStreamItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGatewayStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/binance_market_data.gateway.v1.BinanceMarketDataGatewayService/GetGatewayStatus',
            binance__market__data_dot_gateway_dot_v1_dot_gateway__messages__pb2.GatewayStatusRequest.SerializeToString,
            binance__market__data_dot_gateway_dot_v1_dot_gateway__messages__pb2.GatewayStatusSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
