"""Public enums for BinanceMarketData contracts.

All enums use StrEnum for JSON and cross-language readability.
Values are stable — adding new members is generally compatible,
removing or renaming existing members is BREAKING.
"""

from enum import StrEnum


class Venue(StrEnum):
    BINANCE = "BINANCE"


class Market(StrEnum):
    SPOT = "SPOT"
    USD_M_PERPETUAL = "USD_M_PERPETUAL"


class Stream(StrEnum):
    DIFF_DEPTH = "DIFF_DEPTH"
    AGG_TRADE = "AGG_TRADE"
    BOOK_TICKER = "BOOK_TICKER"
    DEPTH_SNAPSHOT = "DEPTH_SNAPSHOT"


class ReliabilityState(StrEnum):
    COMPLETE = "COMPLETE"
    COMPLETE_WITH_DUPLICATES = "COMPLETE_WITH_DUPLICATES"
    DEGRADED = "DEGRADED"
    GAP_PRESENT = "GAP_PRESENT"
    UNRELIABLE = "UNRELIABLE"
    UNKNOWN = "UNKNOWN"


class HealthState(StrEnum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    UNRELIABLE = "UNRELIABLE"
    UNAVAILABLE = "UNAVAILABLE"


class QualityFlag(StrEnum):
    """Quality flags describe data facts — what is observed about the data.

    These are distinct from ReasonCode which explains Health state judgments.
    """

    DUPLICATE = "DUPLICATE"
    OUT_OF_ORDER = "OUT_OF_ORDER"
    SEQUENCE_GAP = "SEQUENCE_GAP"
    ORDERBOOK_RESYNC = "ORDERBOOK_RESYNC"
    SNAPSHOT_BRIDGE_PENDING = "SNAPSHOT_BRIDGE_PENDING"
    SNAPSHOT_TOO_OLD = "SNAPSHOT_TOO_OLD"
    BOOTSTRAP_BUFFER_OVERFLOW = "BOOTSTRAP_BUFFER_OVERFLOW"
    RECOVERED_TAIL = "RECOVERED_TAIL"
    MALFORMED_PAYLOAD = "MALFORMED_PAYLOAD"
    EXCHANGE_TIME_MISSING = "EXCHANGE_TIME_MISSING"
    RECEIVE_CLOCK_DISCONTINUITY = "RECEIVE_CLOCK_DISCONTINUITY"
    SLOW_CONSUMER_GAP = "SLOW_CONSUMER_GAP"
    PRODUCER_RESTART = "PRODUCER_RESTART"
    OVERLAP = "OVERLAP"
    IDENTITY_CONFLICT = "IDENTITY_CONFLICT"
    CROSSED_BOOK = "CROSSED_BOOK"


class ReasonCode(StrEnum):
    """Reason codes explain Health state judgments — why a state was chosen."""

    CONNECTION_LOST = "CONNECTION_LOST"
    CONNECTION_RESUMED = "CONNECTION_RESUMED"
    PING_TIMEOUT = "PING_TIMEOUT"
    LAST_MESSAGE_AGE_HIGH = "LAST_MESSAGE_AGE_HIGH"
    RECEIVE_LATENCY_HIGH = "RECEIVE_LATENCY_HIGH"
    PUBLISH_LATENCY_HIGH = "PUBLISH_LATENCY_HIGH"
    SEQUENCE_GAP_DETECTED = "SEQUENCE_GAP_DETECTED"
    SEQUENCE_GAP_TOO_LARGE = "SEQUENCE_GAP_TOO_LARGE"
    RESYNC_IN_PROGRESS = "RESYNC_IN_PROGRESS"
    RESYNC_FAILED = "RESYNC_FAILED"
    BOOK_NOT_SYNCHRONIZED = "BOOK_NOT_SYNCHRONIZED"
    BOOK_CROSSED = "BOOK_CROSSED"
    BOOK_EMPTY = "BOOK_EMPTY"
    RECORDER_STALLED = "RECORDER_STALLED"
    GATEWAY_STALLED = "GATEWAY_STALLED"
    DIVERGENCE_DETECTED = "DIVERGENCE_DETECTED"
    DISK_SPACE_LOW = "DISK_SPACE_LOW"
    QUEUE_BACKLOG = "QUEUE_BACKLOG"
    ARCHIVE_BACKLOG = "ARCHIVE_BACKLOG"
    CONFIGURATION_ERROR = "CONFIGURATION_ERROR"


class ContractStatus(StrEnum):
    DRAFT = "DRAFT"
    PROPOSED = "PROPOSED"
    ACCEPTED = "ACCEPTED"
    DEPRECATED = "DEPRECATED"
    REMOVED = "REMOVED"


class ConnectionState(StrEnum):
    CONNECTING = "CONNECTING"
    CONNECTED = "CONNECTED"
    RECONNECTING = "RECONNECTING"
    DISCONNECTED = "DISCONNECTED"
    FAILED = "FAILED"


class ResyncState(StrEnum):
    SYNCHRONIZED = "SYNCHRONIZED"
    RESYNC_REQUIRED = "RESYNC_REQUIRED"
    RESYNC_IN_PROGRESS = "RESYNC_IN_PROGRESS"
    RECOVERED = "RECOVERED"
    RESYNC_FAILED = "RESYNC_FAILED"


class SnapshotSource(StrEnum):
    GATEWAY_LIVE = "GATEWAY_LIVE"
    RECORDER_REPLAY = "RECORDER_REPLAY"
    HISTORY_REPLAY = "HISTORY_REPLAY"


class ReplayClock(StrEnum):
    RECEIVE_TIME = "RECEIVE_TIME"
    EXCHANGE_TIME = "EXCHANGE_TIME"


class MissingExchangeTimePolicy(StrEnum):
    ERROR = "ERROR"
    EXCLUDE = "EXCLUDE"
    FALLBACK_RECEIVE = "FALLBACK_RECEIVE"


class GapPolicy(StrEnum):
    ERROR = "ERROR"
    INCLUDE = "INCLUDE"
    EXCLUDE = "EXCLUDE"


class DeliveryMode(StrEnum):
    CONTIGUOUS_EVENTS = "CONTIGUOUS_EVENTS"
    LATEST_STATE = "LATEST_STATE"


class InitialSnapshotMode(StrEnum):
    NONE = "NONE"
    REQUIRED = "REQUIRED"


class ConsumerGapReason(StrEnum):
    SLOW_CONSUMER = "SLOW_CONSUMER"
    RESUME_NOT_AVAILABLE = "RESUME_NOT_AVAILABLE"
    UPSTREAM_SEQUENCE_GAP = "UPSTREAM_SEQUENCE_GAP"
    GATEWAY_RESTART = "GATEWAY_RESTART"
    CONNECTION_GENERATION_CHANGED = "CONNECTION_GENERATION_CHANGED"
    SUBSCRIPTION_RECONFIGURED = "SUBSCRIPTION_RECONFIGURED"


class RecoveryAction(StrEnum):
    NONE = "NONE"
    RESUBSCRIBE = "RESUBSCRIBE"
    REQUEST_NEW_SNAPSHOT = "REQUEST_NEW_SNAPSHOT"


class StreamLifecycleState(StrEnum):
    ACCEPTED = "ACCEPTED"
    SNAPSHOT_PENDING = "SNAPSHOT_PENDING"
    LIVE = "LIVE"
    RESYNC_IN_PROGRESS = "RESYNC_IN_PROGRESS"
    DEGRADED = "DEGRADED"
    CLOSING = "CLOSING"
    CLOSED = "CLOSED"
