"""Proto code generation tool.

Generates Python protobuf and gRPC stubs from .proto files.
Uses grpc_tools.protoc for compilation.

Usage:
    python -m binance_market_data_contracts.proto_codegen           # generate
    python -m binance_market_data_contracts.proto_codegen --check    # drift check
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path
from tempfile import TemporaryDirectory

PACKAGE_DIR = Path(__file__).resolve().parent
PROTO_ROOT = PACKAGE_DIR / "proto"
GENERATED_DIR = PACKAGE_DIR / "wire" / "generated"

GENERATED_HEADER = """\
# DO NOT EDIT — generated by proto_codegen.
# Any manual changes will be overwritten.
"""


def _find_protoc() -> list[str]:
    """Find the grpc_tools protoc compiler."""
    try:
        result = subprocess.run(
            [sys.executable, "-c", "from grpc_tools import protoc; print(protoc.__file__)"],
            capture_output=True,
            text=True,
            check=True,
        )
        return [sys.executable, result.stdout.strip()]
    except (subprocess.CalledProcessError, ImportError):
        pass
    try:
        result = subprocess.run(
            [sys.executable, "-m", "grpc_tools.protoc", "--version"],
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            return [sys.executable, "-m", "grpc_tools.protoc"]
    except Exception:
        pass
    return ["protoc"]


def _collect_proto_files() -> list[Path]:
    return sorted(PROTO_ROOT.rglob("*.proto"))


def _generate(output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)

    protoc = _find_protoc()
    proto_files = _collect_proto_files()
    if not proto_files:
        print("No .proto files found", file=sys.stderr)
        return

    args: list[str] = []
    for proto_file in proto_files:
        args.extend([str(proto_file)])
    args.extend(
        [
            f"--proto_path={PROTO_ROOT}",
            f"--python_out={output_dir}",
            f"--grpc_python_out={output_dir}",
        ]
    )

    result = subprocess.run([*protoc, *args], capture_output=True, text=True)
    if result.returncode != 0:
        print(f"protoc failed:\n{result.stderr}", file=sys.stderr)
        sys.exit(1)

    print(f"Generated {len(proto_files)} proto files to {output_dir}")


def _add_init_files(output_dir: Path) -> None:
    """Add __init__.py files to directories that need them."""
    for path in output_dir.rglob("*"):
        if path.is_dir() and path != output_dir:
            init_file = path / "__init__.py"
            if not init_file.exists():
                init_file.write_text("")
    # Also ensure root has __init__.py
    root_init = output_dir / "__init__.py"
    if not root_init.exists():
        root_init.write_text("")


def _collect_generated_files(base_dir: Path) -> set[str]:
    files: set[str] = set()
    for f in base_dir.rglob("*"):
        if f.is_file() and "__pycache__" not in f.parts:
            files.add(str(f.relative_to(base_dir)))
    return files


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate protobuf Python stubs")
    parser.add_argument("--check", action="store_true", help="Check for drift (exit non-zero if dirty)")
    args_cli = parser.parse_args()

    if args_cli.check:
        with TemporaryDirectory() as tmp:
            tmp_dir = Path(tmp)
            _generate(tmp_dir)
            _add_init_files(tmp_dir)

            repo_files = _collect_generated_files(GENERATED_DIR)
            tmp_files = _collect_generated_files(tmp_dir)

            all_files = repo_files | tmp_files
            dirty = False

            for fname in sorted(all_files):
                repo_path = GENERATED_DIR / fname
                tmp_path = tmp_dir / fname
                if not repo_path.exists():
                    print(f"  MISSING in repo: {fname}")
                    dirty = True
                elif not tmp_path.exists():
                    print(f"  EXTRA in repo: {fname}")
                    dirty = True
                elif repo_path.read_bytes() != tmp_path.read_bytes():
                    print(f"  DRIFT: {fname}")
                    dirty = True

            if dirty:
                print("\nGenerated code has drifted. Run: python -m binance_market_data_contracts.proto_codegen")
                sys.exit(1)
            print("Generated code matches .proto sources.")
            sys.exit(0)

    GENERATED_DIR.mkdir(parents=True, exist_ok=True)

    _generate(GENERATED_DIR)
    _add_init_files(GENERATED_DIR)

    print(f"Proto code generation complete: {GENERATED_DIR}")


if __name__ == "__main__":
    main()
