# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: binance_market_data/common/v1/metadata.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'binance_market_data/common/v1/metadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from binance_market_data.common.v1 import enums_pb2 as binance__market__data_dot_common_dot_v1_dot_enums__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,binance_market_data/common/v1/metadata.proto\x12\x1d\x62inance_market_data.common.v1\x1a)binance_market_data/common/v1/enums.proto\"-\n\nPriceLevel\x12\r\n\x05price\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\t\"\xa2\x05\n\rEventMetadata\x12\x33\n\x05venue\x18\x01 \x01(\x0e\x32$.binance_market_data.common.v1.Venue\x12\x35\n\x06market\x18\x02 \x01(\x0e\x32%.binance_market_data.common.v1.Market\x12\x0e\n\x06symbol\x18\x03 \x01(\t\x12\x10\n\x08producer\x18\x04 \x01(\t\x12\x18\n\x10producer_version\x18\x05 \x01(\t\x12\x15\n\rconnection_id\x18\x06 \x01(\t\x12\x35\n\x06stream\x18\x07 \x01(\x0e\x32%.binance_market_data.common.v1.Stream\x12\x16\n\x0eschema_version\x18\x08 \x01(\t\x12#\n\x16\x65xchange_event_time_ms\x18\t \x01(\x04H\x00\x88\x01\x01\x12#\n\x16\x65xchange_trade_time_ms\x18\n \x01(\x04H\x01\x88\x01\x01\x12)\n\x1c\x65xchange_transaction_time_ms\x18\x0b \x01(\x04H\x02\x88\x01\x01\x12 \n\x13receive_time_utc_ns\x18\x0c \x01(\x04H\x03\x88\x01\x01\x12!\n\x14receive_monotonic_ns\x18\r \x01(\x04H\x04\x88\x01\x01\x12\x41\n\rquality_flags\x18\x0e \x03(\x0e\x32*.binance_market_data.common.v1.QualityFlagB\x19\n\x17_exchange_event_time_msB\x19\n\x17_exchange_trade_time_msB\x1f\n\x1d_exchange_transaction_time_msB\x16\n\x14_receive_time_utc_nsB\x17\n\x15_receive_monotonic_ns\"\x93\x02\n\x10\x45nvelopeMetadata\x12\x18\n\x10protocol_version\x18\x01 \x01(\t\x12\x1b\n\x13gateway_instance_id\x18\x02 \x01(\t\x12\x17\n\x0fsubscription_id\x18\x03 \x01(\t\x12\"\n\x15\x63onnection_generation\x18\x04 \x01(\x04H\x00\x88\x01\x01\x12\x18\n\x10session_sequence\x18\x05 \x01(\x04\x12\x1b\n\x13publish_time_utc_ns\x18\x06 \x01(\x04\x12!\n\x14publish_monotonic_ns\x18\x07 \x01(\x04H\x01\x88\x01\x01\x42\x18\n\x16_connection_generationB\x17\n\x15_publish_monotonic_nsBOZMgithub.com/tomohikoAmada/BinanceMarketDataContracts/gen/go/common/v1;commonv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'binance_market_data.common.v1.metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZMgithub.com/tomohikoAmada/BinanceMarketDataContracts/gen/go/common/v1;commonv1'
  _globals['_PRICELEVEL']._serialized_start=122
  _globals['_PRICELEVEL']._serialized_end=167
  _globals['_EVENTMETADATA']._serialized_start=170
  _globals['_EVENTMETADATA']._serialized_end=844
  _globals['_ENVELOPEMETADATA']._serialized_start=847
  _globals['_ENVELOPEMETADATA']._serialized_end=1122
# @@protoc_insertion_point(module_scope)
